### ISSUE TITLE
Null pointer Exception when attempting to import NovaSAR data

### ISSUE THREAD

**Issue by sposerina** [bcdev/snap-novasar-reader#1]
I get a null pointer exception at line 373 of NovaSARProductDirectory.java when trying to import a product

double calConstant = imageAttributes.getElement("CalibrationConstant").getAttributeDouble("CalibrationConstant", 1.0);

I fixed this locally and can submit in a pull request.

**Comment by marpet** [comment]
Hi sposerina, Thanks for pointing this out. 
A pull request would be very much appreciated.
