### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by simmonsja** [bcdev/snap-novasar-reader#9]
Hi, 
Thanks for your work in building this reader! I was having some troubles building with maven - getting some issues resolving the dependencies for the project. I hacked together a solution that built by updating the versions in the pom.xml file bumping to:

```
<snap.version>9.0.2</snap.version>
<s1tbx.version>9.0.0</s1tbx.version>
<javahelp.version>2.0.05</javahelp.version>
```

However - I have no idea what I am doing or how SNAP toolboxes work. I'm unsure if there may have been any internal functionality that was reliant on specific versions of dependencies. If it doesn't break anything, happy to submit a tiny PR for the change if helpful.
Cheers,
Josh

**Comment by marpet** [comment]
Thank you for pointing that out.
I've set both version to the current main version 9.0.0.
There is now need for the latest versions.
The old versions didn't work anymore because, there were issues with our maven repository and some of the old library version got lost.

**Comment by simmonsja** [comment]
Thanks for fixing that so swiftly - builds fine now thanks!
